### ISSUE TITLE
Building a Serverless Telegram Bot on AWS - the serverless.env.yml file

### ISSUE THREAD

**Issue by suntong** [muhannad0/muhannad0.github.io#1]
Hi

Thanks for the very useful article 

**Building a Serverless Telegram Bot on AWS**   
https://muhannad0.github.io/post/serverless-telegram-bot-on-aws/

In which it has:

```yml
# set the BOT_TOKEN as an environment variable so that it 
# is accessible to the function

# define env variables under provider section
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    BOT_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}
```

So what's this `serverless.env.yml` file looks like please?

Sorry to post this question as issue, as I found no way to comment on the blog. 

thanks
